In [10]:
import numpy as np 
 
list=[1,3,4,4] 
arr=np.array(list) 
print(f"{arr} and the type of this data is{type(arr)}") 
 
twodim=np.zeros((2,3,2)) 
print(twodim) 
twodim=np.append(twodim[0],44) 
print(twodim)

[1 3 4 4] and the type of this data is<class 'numpy.ndarray'>
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[ 0.  0.  0.  0.  0.  0. 44.]


In [11]:
import numpy as np 
arr=np.arange(1,5) 
print(arr) 
re=arr.reshape(2,2) 
print(re) 
transpose=re.T 
print(transpose) 
mul=np.dot(re,re.T) 
print(mul) 
mul2=np.dot(re.T,re) 
print(mul2)

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[ 5 11]
 [11 25]]
[[10 14]
 [14 20]]


In [12]:
import numpy as np 
import random  
# Create a 1D array with 12 elements 
arr = np.arange(12)  
print("Original:", arr) 

# Reshape into a 2D matrix (3 rows, 4 columns) 
matrix = arr.reshape(3, 4) 
print("\nReshaped (3x4):\n", matrix) 

# Check attributes 
print(f"\nShape: {matrix.shape}") # (3, 4) 
print(f"Dimensions: {matrix.ndim}") # 2 
print(f"Data Type: {matrix.dtype}") # int32 or int64 
# The element at index [row=2, col=3] 
element = matrix[2, 3] 
print(f"Element at [2, 3]: {element}") 

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Shape: (3, 4)
Dimensions: 2
Data Type: int64
Element at [2, 3]: 11


In [13]:
#using function
import numpy as np
def arradd(arr2): 
    
    arr1 = [1, 2, 3, 4, 5] 
    arr1=np.array(arr1)
    arr2=np.array(arr2)
    new_arr = arr1 + arr2  
    print(new_arr) 

arradd([2, 3, 4, 5, 6]) 

[ 3  5  7  9 11]


In [14]:
import numpy as np 
 
arr = np.random.randint(1, 10, 9)   
arr = arr.reshape(3, 3)              
print(arr) 
print(f"Shape: {arr.shape}") 
print(f"Size:  {arr.size}") 
print(f"NDim:  {arr.ndim}")

[[9 4 7]
 [9 3 6]
 [4 1 1]]
Shape: (3, 3)
Size:  9
NDim:  2


In [15]:
import numpy as np 
arrp=np.arange(15).reshape((3, 5)) 
print(arrp)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [18]:
def get_ndim(arr): 
   return arr.ndim,arr.size,arr.shape 
arr_2d = np.array([ 
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12] 
]) 
 
print( get_ndim(arr_2d)) 
arr_3d = np.array([ 
    [ 
        [1, 2, 3, 4], 
        [5, 6, 7, 8], 
 
        [9, 10, 11, 12] 
    ], 
    [ 
        [13, 14, 15, 16], 
        [17, 18, 19, 20], 
        [21, 22, 23, 24] 
    ] 
]) 
 
print( get_ndim(arr_3d)) 

(2, 12, (3, 4))
(3, 24, (2, 3, 4))


Originalarray: [5 2 9 1 7]
Sortedarray: [1 2 5 7 9]
Originalarray:
 [[3 1 2]
 [6 4 5]]
Row-wisesorted:
 [[1 2 3]
 [4 5 6]]
Column-wisesorted:
 [[3 1 2]
 [6 4 5]]


In [21]:
import numpy as np 
arr = np.array([5, 2, 9, 1, 7]) 
sorted_arr = np.sort(arr) 
print("Originalarray:", arr) 
print("Sortedarray:", sorted_arr) 
import numpy as np 
arr = np.array([ 
    [3, 1, 2], 
    [6, 4, 5] 
 
]) 
row_sort = np.sort(arr, axis=1) 
col_sort = np.sort(arr, axis=0) 
print("Originalarray:\n", arr) 
print("Row-wisesorted:\n", row_sort) 
print("Column-wisesorted:\n", col_sort)

Originalarray: [5 2 9 1 7]
Sortedarray: [1 2 5 7 9]
Originalarray:
 [[3 1 2]
 [6 4 5]]
Row-wisesorted:
 [[1 2 3]
 [4 5 6]]
Column-wisesorted:
 [[3 1 2]
 [6 4 5]]


In [23]:
import numpy as np 
 
a = np.array([1, 2, 3]) 
 
b = np.array([4, 5, 6]) 
 
print("Addition:", a + b) 
print("Subtraction:", a - b) 
print("Multiplication:", a * b) 
print("Division:", a / b) 

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [25]:
import numpy as np 
 
arr = np.array([10, 20, 30, 40, 50]) 
print(arr[arr > 25])
arr = np.array([10, 20, 30, 40, 50]) 
index = [0, 2, 4] 
print(arr[index])

[30 40 50]
[10 30 50]


In [26]:
import numpy as np 
arr = np.array([1, 4, 9, 16]) 
print("Square Root:", np.sqrt(arr)) 
print("Exponential:", np.exp(arr)) 
print("Logarithm:", np.log(arr))

Square Root: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Logarithm: [0.         1.38629436 2.19722458 2.77258872]
