In [52]:
import numpy as np

list=[1,3,4,4]
arr=np.array(list)
print(f"{arr} and the type of this data is{type(arr)}")

twodim=np.zeros((2,3,2))
print(twodim)
twodim=np.append(twodim[0],44)
print(twodim)

[1 3 4 4] and the type of this data is<class 'numpy.ndarray'>
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[ 0.  0.  0.  0.  0.  0. 44.]


In [55]:
import numpy as np
arr=np.arange(1,5)
print(arr)
re=arr.reshape(2,2)
print(re)
transpose=re.T
print(transpose)
mul=np.dot(re,re.T)
print(mul)
mul2=np.dot(re.T,re)
print(mul2)

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[ 5 11]
 [11 25]]
[[10 14]
 [14 20]]


In [57]:
import numpy as np
import random 
# Create a 1D array with 12 elements
arr = np.arange(12) 
print("Original:", arr)

# Reshape into a 2D matrix (3 rows, 4 columns)
matrix = arr.reshape(3, 4)
print("\nReshaped (3x4):\n", matrix)

# Check attributes
print(f"\nShape: {matrix.shape}") # (3, 4)
print(f"Dimensions: {matrix.ndim}") # 2
print(f"Data Type: {matrix.dtype}") # int32 or int64
# The element at index [row=2, col=3]
element = matrix[2, 3]

print(f"Element at [2, 3]: {element}")

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Shape: (3, 4)
Dimensions: 2
Data Type: int64
Element at [2, 3]: 11
