In [52]:
import numpy as np

list=[1,3,4,4]
arr=np.array(list)
print(f"{arr} and the type of this data is{type(arr)}")

twodim=np.zeros((2,3,2))
print(twodim)
twodim=np.append(twodim[0],44)
print(twodim)

[1 3 4 4] and the type of this data is<class 'numpy.ndarray'>
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[ 0.  0.  0.  0.  0.  0. 44.]


In [55]:
import numpy as np
arr=np.arange(1,5)
print(arr)
re=arr.reshape(2,2)
print(re)
transpose=re.T
print(transpose)
mul=np.dot(re,re.T)
print(mul)
mul2=np.dot(re.T,re)
print(mul2)

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[ 5 11]
 [11 25]]
[[10 14]
 [14 20]]


In [57]:
import numpy as np
import random 
# Create a 1D array with 12 elements
arr = np.arange(12) 
print("Original:", arr)

# Reshape into a 2D matrix (3 rows, 4 columns)
matrix = arr.reshape(3, 4)
print("\nReshaped (3x4):\n", matrix)

# Check attributes
print(f"\nShape: {matrix.shape}") # (3, 4)
print(f"Dimensions: {matrix.ndim}") # 2
print(f"Data Type: {matrix.dtype}") # int32 or int64
# The element at index [row=2, col=3]
element = matrix[2, 3]

print(f"Element at [2, 3]: {element}")

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Shape: (3, 4)
Dimensions: 2
Data Type: int64
Element at [2, 3]: 11


In [ ]:
def arradd(arr2):
    arr1 = [1, 2, 3, 4, 5]
   
   
    new_arr = arr1 + arr2 
    print(new_arr)

arradd([2, 3, 4, 5, 6])


[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]


In [16]:
import numpy as np

arr = np.random.randint(1, 10, 9)  
arr = arr.reshape(3, 3)             
print(arr)
print(f"Shape: {arr.shape}")
print(f"Size:  {arr.size}")
print(f"NDim:  {arr.ndim}")


[[4 5 3]
 [5 6 9]
 [8 7 4]]
Shape: (3, 3)
Size:  9
NDim:  2


In [17]:
import numpy as np
arrp=np.arange(15).reshape((3, 5))
print(arrp)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
import numpy as np

def get_ndim(arr):
      return arr.ndim,arr.size,arr.shape
arr_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print( get_ndim(arr_2d))
arr_3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print( get_ndim(arr_3d))
